# Generated by Django 4.2.dev20220526083951 on 2022-06-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, verbose_name='First Name')),
                ('lname', models.CharField(max_length=200, verbose_name='Last Name')),
                ('oname', models.CharField(blank=True, max_length=200, verbose_name='Other Name')),
                ('planguage', models.CharField(max_length=50, verbose_name='Language')),
                ('university', models.CharField(blank=True, max_length=100, verbose_name='university')),
                ('more', models.TextField(blank=True, verbose_name='More About You')),
                ('resume', models.URLField(blank=True, verbose_name='CV link')),
                ('mail', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
            ],
        ),
    ]
